### ISSUE TITLE
Encore unable to start after update to 1.41.10 Golang

### ISSUE THREAD

**Issue by raff-wakflo** [encoredev/encore#1472]
<img width="1428" alt="Screenshot 2024-10-11 at 4 40 20 PM" src="https://github.com/user-attachments/assets/aaa1ccc0-37f9-48dc-b0b3-9abb1ba11c67">

**Comment by raff-wakflo** [comment]
Even after restarting my computer I keep getting `encore: restarting daemon due to configuration change.`

**Comment by eandre** [comment]
Thanks for the report! This should be fixed in v1.41.11. Can you update and verify? Thanks :)

**Comment by raff-wakflo** [comment]
> Thanks for the report! This should be fixed in v1.41.11. Can you update and verify? Thanks :)
I'm not having that error but now encore run won't event succeed or start. I have uninstalled encore and installed to no avail. Right now completely blocked by this issue.

**Comment by eandre** [comment]
Can you provide a full daemon log from running `encore run` where it blocks?

**Comment by raff-wakflo** [comment]
@eandre 

```
1:52PM INF writing output to /Users/rexraphael/Library/Caches/encore/daemon.log
13:52:35 INF encr.dev/cli/cmd/encore/daemon/daemon.go:562 > listening on port component=runtime port=9600
13:52:35 INF encr.dev/cli/cmd/encore/daemon/daemon.go:562 > listening on port component=debug port=9700
13:52:35 INF encr.dev/cli/cmd/encore/daemon/daemon.go:562 > listening on port component=dashboard port=9400
13:52:35 INF encr.dev/cli/cmd/encore/daemon/daemon.go:562 > listening on port component=dbproxy port=9500
13:52:35 INF encr.dev/cli/cmd/encore/daemon/daemon.go:255 > serving debug addr=127.0.0.1:9700
13:52:35 INF encr.dev/cli/cmd/encore/daemon/daemon.go:249 > serving dash addr=127.0.0.1:9400
13:52:35 INF encr.dev/cli/cmd/encore/daemon/daemon.go:230 > serving daemon addr=/Users/rexraphael/Library/Caches/encore/encored.sock
13:52:35 INF encr.dev/cli/cmd/encore/daemon/daemon.go:237 > serving runtime addr=127.0.0.1:9600
13:52:35 INF encr.dev/cli/cmd/encore/daemon/daemon.go:244 > serving dbproxy addr=127.0.0.1:9500
13:53:35 INF encr.dev/cli/daemon/engine/trace2/sqlite/write.go:60 > initiating trace event cleanup sweep
13:54:35 INF encr.dev/cli/daemon/engine/trace2/sqlite/write.go:60 > initiatin
```

**Comment by raff-wakflo** [comment]
I also tried to create a new app via templates and the CLI is stuck at Downloaded template graphql. So I think it's some connection issue. 

I can confirm the same version runs on my friends computer but mine just freezes and sometimes it eats up my ram and forces me to restart my computer.

I have tried everything from VPN, to reinstalling, even manually and still does not work. Every other program works just fine on my computer.

I'm think maybe its the new Mac OS 15.0.1 and maybe some permission issues
